services:
  node:
    restart: always
    build: .
    container_name: "node"
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "./src"
        target: "/home"
