version: '3'

services:
  node:
    restart: always
    build: .
    container_name: 'node'
    tty: true
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: "./src"
        target: "/home"
